spring:
  datasource:
    url: jdbc:mysql://mysql-licorera-full.mysql.database.azure.com:3306/licorera?useSSL=true&requireSSL=false
    username: santiago23
    password: LauraValentina19
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # Expose all management endpoints

