name: Build and deploy WAR app to Azure Web App - LicoreraFull

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: .
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_348B9733AC1A4C22B98663DCBB5BB28B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AA5925EDC034830A8B8F2F1A79877F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6962D2E7CB484E0DB97C0AEE3E7C7553 }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'LicoreraFull'
          slot-name: 'Production'
          package: '*.jar'
